### ISSUE TITLE
Hi! There are maybe some mistakes in your codes. Is the implementation of "uaggan" correct? I guess the attention part is missing in "uaggan_model".

### ISSUE THREAD

**Issue by DLwbm123** [yhlleo/uaggan#1]

**Comment by yhlleo** [comment]
I'm sorry, I didn't update the final version of the codes. There are some mistakes indeed. I'll fix it as soon as possible.

**Comment by DLwbm123** [comment]
Thanks for your reply! I am trying to re-implement the framework too. Waiting for your code! : )

**Comment by yhlleo** [comment]
Sure, I'll submit my implemented code as soon as possible. btw, I have submitted the network modules.

**Comment by yhlleo** [comment]
I have update the codes today. And, experimental results will be updated later. If there are any problems, please let me know. Thanks. @DLwbm123

**Comment by DLwbm123** [comment]
Yeah. I have tried with the code. Unfortunately, the results seemed not good.  The attention maps are all black(zeros) for both ImageA and ImageB. Could you check if something was wrong with the attention mechanism?

**Comment by yhlleo** [comment]
Sure, I have tested, you're right. I'll fix it~

**Comment by yhlleo** [comment]
It seems that such issue happens only when the weights of cycle consistency loss are too large. At the beginning, I followed the tensorflow code and the published paper, but it failed. After reducing the weights(from `10.0` to `1.0`), it works well. Except that, I modified the discriminator part. @DLwbm123

**Comment by yhlleo** [comment]
After adding early stopping, I guess this project is finished. If you have any questions, please let me know. Thanks. @DLwbm123
