### ISSUE TITLE
Error during Test

### ISSUE THREAD

**Issue by deep0learning** [yhlleo/uaggan#3]
Hi,
I have gotten the following error during the test phase?
  File "test.py", line 47, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/media/deep/DATA/New_CODE/working3/amena/uaggan/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/media/deep/DATA/New_CODE/working3/amena/uaggan/models/uag_gan_model.py", line 27, in __init__
    BaseModel.__init__(self, opt)
  File "/media/deep/DATA/New_CODE/working3/amena/uaggan/models/base_model.py", line 35, in __init__
    self.device = torch.device('cuda:{}'.format(self.gpu_ids[0])) if self.gpu_ids else torch.device('cpu')  # get device name: CPU or GPU
AttributeError: module 'torch' has no attribute 'device'

**Comment by yhlleo** [comment]
What's your version of pytorch. Do your follow the configuration of `environment.yml`?

**Comment by deep0learning** [comment]
Yes, I followed.

The pytorch version is 0.4.1

**Comment by deep0learning** [comment]
Training is ok but got an error in the test phase.

**Comment by yhlleo** [comment]
I updated the file `scripts/test_uaggan.sh`, in which I forget to assign value to `gpu_ids`. @deep0learning

**Comment by deep0learning** [comment]
Thank you. It works now.

**Comment by yhlleo** [comment]
You're welcome. @deep0learning
