### ISSUE TITLE
Hi！One question again. :) The results seem not so good when I apply it to my own data. I think that the images sent to the discriminator should multiply with their associated masks as illustrated in the original paper. Look forward to youre reply!

### ISSUE THREAD

**Issue by DLwbm123** [yhlleo/uaggan#4]

**Comment by yhlleo** [comment]
Yes,I tested it, but the results were similar.

**Comment by yhlleo** [comment]
I have updated the code to support using generated image multiplied by the mask as input for the discriminator. You can set it by changing the parameter `--use_mask_for_D`. 

See the configuration in the [`scripts/train_uaggan.sh`](https://github.com/yhlleo/uaggan/blob/master/scripts/train_uaggan.sh#L12).

**Comment by DLwbm123** [comment]
Great thanks!
